export const orgaosExpedidores = [
    { label: "AC", value: "AC" },
    { label: "AL", value: "AL" },
    { label: "AP", value: "AP" },
    { label: "AM", value: "AM" },
    { label: "BA", value: "BA" },
    { label: "CE", value: "CE" },
    { label: "DF", value: "DF" },
    { label: "ES", value: "ES" },
    { label: "GO", value: "GO" },
    { label: "MA", value: "MA" },
    { label: "MT", value: "MT" },
    { label: "MS", value: "MS" },
    { label: "MG", value: "MG" },
    { label: "PA", value: "PA" },
    { label: "PB", value: "PB" },
    { label: "PR", value: "PR" },
    { label: "PE", value: "PE" },
    { label: "PI", value: "PI" },
    { label: "RJ", value: "RJ" },
    { label: "RN", value: "RN" },
    { label: "RS", value: "RS" },
    { label: "RO", value: "RO" },
    { label: "RR", value: "RR" },
    { label: "SC", value: "SC" },
    { label: "SP", value: "SP" },
    { label: "SE", value: "SE" },
    { label: "TO", value: "TO" },
    { label: "Outro", value: "OUTRO" },
  ];
  
  export const estadoCivil = [
    {label: "Casado(a)", value: "Casado(a)"},
    {label: "Solteiro(a)", value: "Solteiro(a)"},
    {label: "Divorciado(a)", value: "Casado(Divorciado)"},
    {label: "Viúvo(a)", value: "CasadoViúvoa)"},
    {label: "Outro(a)", value: "Outro(a)"},
  ];

  export const cotas = [
    {label: "Cota 1", value: "Cota 1"},
    {label: "Cota 2", value: "Cota 2"},
    {label: "Cota 3", value: "Cota 3"},
    {label: "Cota 4", value: "Cota 4"},
    {label: "Cota 5", value: "Cota 5"},
    {label: "Cota 6", value: "Cota 6"},
    {label: "Cota 7", value: "Cota 7"},
    {label: "Cota 8", value: "Cota 8"},
    {label: "Cota 9", value: "Cota 9"},
    {label: "Cota 10", value: "Cota 10"},
  ];

  export const blocos = [
    {label: "Bloco 1 (A) Bergantim", value: "Bloco 1 (A) Bergantim" },
    {label: "Bloco 2 (B) Dakkar", value: "Bloco 2 (B) Dakkar"},
    {label: "Bloco 3 (C) Galeão", value: "Bloco 3 (C) Galeão"},
    {label: "Bloco 4 (D) Trirreme", value: "Bloco 4 (D) Trirreme"},
  ];

  export const parcelas = [
    {label: "1 Parcela de R$ 540,00", value: 1 },
    {label: "2 Parcelas de R$ 270,00", value: 2},
    {label: "4 Parcelas de R$ 135,00", value: 3},
    {label: "8 Parcelas de R$67,50", value: 4},
    {label: "12 Parcelas de R$ 45,00 ", value: 5},
  ];

  export const apartamentos = [
    {label: "101", value: "101"},
    {label: "102", value: "102"},
    {label: "103", value: "103"},
    {label: "104", value: "104"},
    {label: "105", value: "105"},
    {label: "106", value: "106"},
    {label: "107", value: "107"},
    {label: "108", value: "108"},
    {label: "201", value: "201"},
    {label: "202", value: "202"},
    {label: "203", value: "203"},
    {label: "204", value: "204"},
    {label: "205", value: "205"},
    {label: "206", value: "206"},
    {label: "207", value: "207"},
    {label: "208", value: "208"},
    {label: "301", value: "301"},
    {label: "302", value: "302"},
    {label: "303", value: "303"},
    {label: "304", value: "304"},
    {label: "305", value: "305"},
    {label: "306", value: "306"},
    {label: "307", value: "307"},
    {label: "308", value: "308"},
    {label: "401", value: "401"},
    {label: "402", value: "402"},
    {label: "403", value: "403"},
    {label: "404", value: "404"},
    {label: "405", value: "405"},
    {label: "406", value: "406"},
    {label: "407", value: "407"},
    {label: "408", value: "408"},
    {label: "501", value: "501"},
    {label: "502", value: "502"},
    {label: "503", value: "503"},
    {label: "504", value: "504"},
    {label: "505", value: "505"},
    {label: "506", value: "506"},
    {label: "507", value: "507"},
    {label: "508", value: "508"},
  ]